name: Publish Helm Chart to Quay.io

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
      - name: Lint Helm Chart
        run: helm lint ./
      - name: Package and Push Chart to Quay.io
        run: |
          helm package ./ -d ./
          export HELM_EXPERIMENTAL_OCI=1
          helm registry login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io
          helm push ./*.tgz oci://quay.io/crozltd
          helm registry logout quay.io
